spring.application.name=agendamento-notificacao-api

Datasource.url=jdbc:postgresql://localhost:5432/db_agendamento
Datasource.username=postgres
Datasource.password=1234
oa.hibernate.ddl-auto=update
oa.show-sql=true
oa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
